language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

# OpenJDK 7 buffer overflow workaround from https://github.com/travis-ci/travis-ci/issues/5227
before_install:
  - cat /etc/hosts # optionally check the content *before*
  - sudo hostname "$(hostname | cut -c1-63)"
  - sed -e "s/^\\(127\\.0\\.0\\.1.*\\)/\\1 $(hostname | cut -c1-63)/" /etc/hosts > /tmp/hosts
  - sudo mv /tmp/hosts /etc/hosts
  - cat /etc/hosts # optionally check the content *after*

install: mvn install -DskipTests=true

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script: 
  - mvn verify -Dskip.test.categories=gui,realtime

sudo: required
cache:
  directories:
    - '$HOME/.m2/repository'

env:
  global:
    secure: "BNmSL7eqM5T2U94LVDArWadTZxL9M5S9XZTDg5DA9pwZwZzH+7ZgTcAfhmBJ0ql9YdVm5usmHKCT1HXXMwL0EfUkYbDSZmfn+uoXSvjgWjNmlU9zV0P1La+lPle878bWjbUev3qgjwpd1zRF1RwADolGQwowj35D8jl+E8DPPSQ="
